@startuml
User --> (Login)


left to right direction
skinparam packageStyle rectangle
rectangle checkout{
(Login) --> (Dashboard)
(Dashboard)  --> (DashboardUpdatesFrsgment) : User will able to see all articles
(DashboardUpdatesFrsgment)  --> (DashBoardFeedsAdapter) : User enter into timeline of article
(DashBoardFeedsAdapter) --> (FeedsSummary): FullView of article
(FeedsSummary) --> (MultiMediaController): User can View/play multimedia file if any
(FeedsSummary) --> (ImageViewPagerAdapter): user can view images if any
}

skinparam nodesep 10
skinparam ranksep 20

note "User should able to view/play audio file in feed." as N2
(Start) .. N2
N2 .. (Use)
@enduml