package com.vam.whitecoats.utils;

public enum NavigationType {
    MY_PROFILE(11),VERIFY_PROFILE(12),OTHER_USER_PROFILE(13),SHARE_UPDATE_OR_CASE(21),SEARCH_LANDING(31),FEED_FULLVIEW(41),
   CHANNEL_TAB(61),MY_PREFERENCE(71),TRENDING_CATEGORY(81),CHANNEL_TIMELINE(62),INVITE_TO_WHITECOATS(53),
    NOTIFICATION_PREFERENCE(83),KNOWLEDGE_FEEDS(91),KNOWLEDGE_DRUG_REFERENCES(92),KNOWLEDGE_MEDICAL_EVENTS(93),COMMUNITY_SPOTLIGHT(101),COMMUNITY_FEEDS(102),
    COMMUNITY_DOCTORS(51),COMMUNITY_ORGANIZATION(103),PROFESSIONAL_FEEDS(111),PROFESSIONAL_SKILLING(112),PROFESSIONAL_OPPORTUNITIES(113),PROFESSIONAL_PARTNERS(114),
    NOTIFICATION_TAB(82),NOTIFICATION_ENABLE_POPUP(115);
    int navigationValue;

    private NavigationType(int mValue) {
        this.navigationValue = mValue;
    }

    public int getNavigationValue() {
        return navigationValue;
    }
}
